version: "3"

services:
  #wordpress:
  #  image: "wordpress:php8.3-apache"
  #  environment:
  #     WORDPRESS_DB_HOST: mysql-master
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpresspassword
  #     WORDPRESS_DB_NAME: wordpress
  #  ports: 
  #    - 5050:80
  #  depends_on:
  #    - mysql-master

  mysql-master:
    image: "mysql:8-master-slave"
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_REPLICATION_PASS: HqAzZkePY6zSERA8XG9FLt
      # The master node cannot be replicated.
      MYSQL_ROLE: master
    command: --server_id=1
    volumes:
      - mysql-master:/var/lib/mysql

  mysql-slave:
    # We use the same custom image
    image: "mysql:8-master-slave"
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_PASS: HqAzZkePY6zSERA8XG9FLt
      MYSQL_MASTER_HOST: mysql-master
      # Role must be assiged to slave
      MYSQL_ROLE: slave
    command: --server_id=2
    volumes:
      - mysql-slave:/var/lib/mysql
    depends_on:
      - mysql-master

volumes:
    mysql-master:
    mysql-slave: